# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jbDsfI6XXO8RVvh9dZgX4ypxtDf4AK0Z
"""

import random


responses = {
    "hello": ["Hello!", "Hi there!", "Hey!"],
    "how are you": ["I'm good, thanks!", "I'm doing well. How about you?", "I'm just a bot, but I'm here to help!"],
    "what's your name": ["I'm a chatbot.", "You can call me AI .", "I don't have a name, but you can call me anything you like."],
    "bye": ["Goodbye!", "See you later!", "Have a great day!"],
    "default": ["I'm not sure I understand.", "Could you please rephrase that?", "I don't have an answer to that."]
}


def get_response(user_input):ok
    user_input = user_input.lower()

    for key in responses:
        if key in user_input:
            return random.choice(responses[key])


    return random.choice(responses["default"])


print("Chatbot: Hello! How can I assist you today?")
while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Chatbot: Goodbye!")
        break
    response = get_response(user_input)
    print("Chatbot:", response)